using System;
using System.Linq.Expressions;

namespace ArrangeMock.Interfaces
{
    public interface IArgumentPassedIn
    {
        void AreSavedTo<T>(Expression<Func<T>> memberAccessExpression);
        void AreSavedTo<T1, T2>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2);
        void AreSavedTo<T1, T2, T3>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3);
        void AreSavedTo<T1, T2, T3, T4>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4);
        void AreSavedTo<T1, T2, T3, T4, T5>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5);
        void AreSavedTo<T1, T2, T3, T4, T5, T6>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10, Expression<Func<T11>> memberAccessExpression11);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10, Expression<Func<T11>> memberAccessExpression11, Expression<Func<T12>> memberAccessExpression12);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10, Expression<Func<T11>> memberAccessExpression11, Expression<Func<T12>> memberAccessExpression12, Expression<Func<T13>> memberAccessExpression13);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10, Expression<Func<T11>> memberAccessExpression11, Expression<Func<T12>> memberAccessExpression12, Expression<Func<T13>> memberAccessExpression13, Expression<Func<T14>> memberAccessExpression14);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10, Expression<Func<T11>> memberAccessExpression11, Expression<Func<T12>> memberAccessExpression12, Expression<Func<T13>> memberAccessExpression13, Expression<Func<T14>> memberAccessExpression14, Expression<Func<T15>> memberAccessExpression15);
        void AreSavedTo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(Expression<Func<T1>> memberAccessExpression1, Expression<Func<T2>> memberAccessExpression2, Expression<Func<T3>> memberAccessExpression3, Expression<Func<T4>> memberAccessExpression4, Expression<Func<T5>> memberAccessExpression5, Expression<Func<T6>> memberAccessExpression6, Expression<Func<T7>> memberAccessExpression7, Expression<Func<T8>> memberAccessExpression8, Expression<Func<T9>> memberAccessExpression9, Expression<Func<T10>> memberAccessExpression10, Expression<Func<T11>> memberAccessExpression11, Expression<Func<T12>> memberAccessExpression12, Expression<Func<T13>> memberAccessExpression13, Expression<Func<T14>> memberAccessExpression14, Expression<Func<T15>> memberAccessExpression15, Expression<Func<T16>> memberAccessExpression16);


        void AreUsedToInvokeAction<T>(Action<T> action);
        void AreUsedToInvokeAction<T1, T2>(Action<T1, T2> action);
        void AreUsedToInvokeAction<T1, T2, T3>(Action<T1, T2, T3> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4>(Action<T1, T2, T3, T4> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5>(Action<T1, T2, T3, T4, T5> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6>(Action<T1, T2, T3, T4, T5, T6> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7>(Action<T1, T2, T3, T4, T5, T6, T7> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8>(Action<T1, T2, T3, T4, T5, T6, T7, T8> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> action);
        void AreUsedToInvokeAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> action);
    }
}